root = "."

[build]
cmd="clear ; make debug"
include_ext = ["c", "h", "png", "tmx"]
exclude_file = ["resources/tmx.ldtk"]
delay = 600
exclude_dir = ["objs", "docs", "deps", ".vscode", "github","vendor"]
bin = "quiet.sh"