name: publishing github pages

on: {
  push: {
    branches: ['master']
  }
}

jobs : {
  build: {
    runs-on: ubuntu-latest ,
    steps: [
      {
        uses: actions/checkout@v2,
        name : Check out repository
      },
      {
        uses : mymindstorm/setup-emsdk@v11,
        name : Setup emsdk,
        with: {
          version: 3.1.9,
          actions-cache-folder: 'emsdk-cache'
        }
      },
      {
        name: Verifying emsdk,
        run : 'emcc --version'
      },
      {
        name: Building App for release,
        run : 'make release'
      },
      {
        name: Installing Binaryen,
        run : 'sudo apt-get install binaryen'
      },
      {
        name: Optimizing wasm for size,
        run: "
          cd docs;
          wasm-opt index.wasm -o output.wasm -Oz;
          mv output.wasm index.wasm;
          chmod +x index.wasm;
          cd -;
        "
      },
      {
        name: Commit Files,
        run : "
          git config --local user.email \"41898282+github-actions[bot]@users.noreply.github.com\";
          git config --local user.name \"github-actions[bot]\";
          git add docs/ --force;
          git commit -m \"Github Actions auto-deploy\" -a;"
      },
      {
        name: Push changes to github-pages,
        uses: ad-m/github-push-action@master,
        with: {
          github_token: "${{ secrets.GIT_GITHUB_TOKEN }}",
          branch: "github-pages",
          force: true  
        }
      }
    ]
  }
}